### ISSUE TITLE
Quelle est la plus grande illusion de la vie?

### ISSUE THREAD

**Issue by valorad** [longyiszh/hello#5]
Demandé par la Black-door dans le jeu vidéo The Elder Scrolls.

**Comment by longyiszh** [comment]
Les sélections carrés, s'il te plaît.

**Comment by valorad** [comment]
A. Sanguine, my brother.

B. Silence, my brother.

C. Innocence, my brother.

D. Sublime, my Brother.

**Comment by longyiszh** [comment]
Le "Silence, my brother"?

**Comment by valorad** [comment]
Non. Le "Innocence, my brother".

**Comment by valorad** [comment]
REF: https://elderscrolls.fandom.com/wiki/The_Black_Door (Visited: 20190213)

**Comment by longyiszh** [comment]
grrrrrr!
